# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

# append some arguments to the commandline;
# accepts anything listed in --help (leading dashes are optional)
# and inline comments are OK if there is 2 spaces before the '#'
[global]
  hist: /cfg/hists/
  p: 80,443 
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # and enable multimedia indexing
  z, qr  # and zeroconf and qrcode (you can comma-separate arguments)
  mtp: .bpm=f,t30,/mtag/audio-bpm.py  # should take ~10sec
  mtp: key=f,t190,/mtag/audio-key.py  # should take ~50sec


# create users:
[accounts]
  phofidda: Snowstorm_Shrine_Overlabor2

# create volumes:
[/]         # create a volume at "/" (the webroot), which will
  .         # share the contents of "." (the current directory)
  accs:
    r: *    
    A: phofidda  
